### ISSUE TITLE
Loading state throws console warning when navigating away before page loads

### ISSUE THREAD

**Issue by jeffvg** [pxblue/react-design-patterns#33]
#### Describe the bug
When selecting loading state example and navigating away to another page throws warning (can't perform a react state update on unmounted component)
#### What is the expected behavior?
No warning

#### What are the steps to reproduce?
1. localhost:3000
2. open dev tools
3. Click on loading state example and wait 1 second then click drawer header to nav back to landing page

#### Screenshots or links to minimum reproduction example
![image](https://user-images.githubusercontent.com/37150565/92270958-f9299f80-eeb4-11ea-88d6-4c44acf4576e.png)

#### Environment

Mac
Chrome

**Comment by joebochill** [comment]
We've run into this before with the asynchronous data load on the resources page on doc-it as well. It's because you are trying to set state on a component which no longer exists. We can work around this by making a few tweaks to the useEffect hook to check if the component still exists before setting the new state (refer to doc-it: https://github.com/pxblue/doc-it/blob/ac537683fdc6b8c3a66d1c1a94cdc6f341cd542d/src/app/components/resources/buttons/BugsButton.tsx#L44).
